# .pre-commit-config.yaml
---
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs_replace
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: checkov
        args:
          - '--quiet'
          - '--skip-check'
          - 'CKV_GCP_43,CKV_GCP_62,CKV_GCP_37,CKV_GCP_38'  # Key Rotation, Bucket log, CSEK

  - repo: git://github.com/adrienverge/yamllint
    rev: v1.26.0
    hooks:
      - id: yamllint
        args: ['-c=.yamllint']

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: 'ansible/roles/deploy_ssh_keys/files'
      - id: trailing-whitespace
      - id: check-merge-conflict
